# see travis-ci.org for details

sudo: required
dist: trusty

install:
    - sudo apt-get -y update
    - sudo apt-get -y install cmake g++-mingw-w64-i686 g++-mingw-w64-x86-64

script:
 - ./development/cmake/scripts/travis.sh

branches:
 only:
   - bleeding-edge-master
   
