# see travis-ci.org for details

language: cpp

install:
 - sudo apt-get remove cmake mingw32-binutils mingw32-runtime mingw32 libqt4-dev qt4-qmake mingw-w64 g++-mingw-w64 gcc-mingw-w64
# downloaded cmake is 32bit
 - sudo apt-get install libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386

script:
 - ./development/cmake/scripts/travis.sh

branches:
 only:
   - bleeding-edge
   
